### ISSUE TITLE
Two laminates overlap each other

### ISSUE THREAD

**Issue by JWS625** [wenbinyugroup/ivabs#60]
Target Design: I was trying to generate mesh for an airfoil with round corner spar. However, whenever I add leading/trailing edge laminates that share the same starting point with the round corner of spar, it can't generate the mesh.

To get better understanding what's going on to the cross-section, I tried avoiding this by having a gap between the starting point of leading/trailing edge laminate and that of round corner. It could successfully generate mesh, but I got two components overlapping each other as shown in the second figure. In the xml file, the leading/trailing edge laminates depend on the spar component.

I don't know if the two input files share the same source issue, but any help would be very appreciated.

![airfoil_config png](https://github.com/wenbinyugroup/ivabs/assets/95206221/c368bb63-b2c7-4ba4-899e-5756fd1063f3)
![corner_overlap png](https://github.com/wenbinyugroup/ivabs/assets/95206221/40edb731-87c4-40eb-972c-73023cace794)

**Comment by unitasium** [comment]
This may be the issue of the trimming function. It has the difficulty of trimming the layer if the tangent directions of the two components are too close to each other. A workaround is to modify the end of the part to be trimmed, so that its end tangent direction is different from that of the cutting component.

A modification of this example is shown below. I exaggerated the modification to make it obvious. You can adjust this region to reduce the size of the hollow part and even fill it with materials.


![image](https://github.com/wenbinyugroup/ivabs/assets/20133519/b5848be9-5055-4f8c-826d-442fc2789eca)

![image](https://github.com/wenbinyugroup/ivabs/assets/20133519/afd02938-784e-4c3c-92a1-d069d8eda5b6)
